<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnowledgeAi.Application\KnowledgeAi.Application.csproj" />
    <ProjectReference Include="..\KnowledgeAi.Infrastructure\KnowledgeAi.Infrastructure.csproj" />
    <ProjectReference Include="..\KnowledgeAi.Domain\KnowledgeAi.Domain.csproj" />
  </ItemGroup>

</Project>
